### ISSUE TITLE
Suggestion: remove plugins

### ISSUE THREAD

**Issue by olegskl** [izaakschroeder/eslint-config-metalab#35]
I failed several Travis builds today for [karma-adana-reporter](https://github.com/olegskl/karma-adana-reporter) because I forgot to install a peer dependency.

~~I was unable to add a codeclimate badge because apparently there's [a security concern](https://docs.codeclimate.com/docs/eslint#supported-plugins) with plugins in general and codeclimate doesn't support the ones required by this config.~~ Scratch that, it seems that they have issues in general.

The eslint-plugin-react must be installed even if the repo doesn't use React at all. There are currently 8 repositories in the [adana-coverage](https://github.com/adana-coverage) group, but only one of them actually has jsx in two fixture files that don't need to be linted at all.

So far these plugins provided me with virtually no benefit. I don't deny their usefulness, but I suppose that they can be added to the project when there is a real need for them.

**Comment by izaakschroeder** [comment]
This is an unfortunate open issue with `eslint`. Ideally these plugins would be listed as `dependencies` instead of as `peerDependencies` and as a consumer you'd never have to know they were included if you didn't use them. The issue tracking this is here: https://github.com/eslint/eslint/issues/3458.

One could propose some alternate solutions:
- Have separate packages/configs for plugins; there could be an `eslint-config-metalab-react`, etc. While you gain the isolation benefits it's a bunch more things to maintain and consumers now have to worry about managing more versions of things too. I need less things to manage in my life. 😄 
- Have only the rules but not the plugins; in some kind of fantasy land maybe 😄  but this will always result in incompatibilities because of rule version changes. There has to be a dependency somewhere.

This situation isn't ideal, but I feel it's the most practical for now (even if a bit extraneous in some situations). I'm really looking forward to the resolution of that open `eslint` issue which should actually resolve this properly. And once it's solved with `eslint`, the consumer facing change will be simple – just remove all the plugin entries `devDependencies`.
